language: cpp
os:
  - osx
script:
  - brew install ./libjdcloud_signer.rb
  - brew uninstall libjdcloud_signer
  - brew install --HEAD ./libjdcloud_signer.rb
  - brew uninstall libjdcloud_signer
cache:
  directories:
    - /usr/local/Homebrew
