language: cpp
os:
  - osx
script:
  - pwd
  - ls
  - brew install ./jdcloud_cli.rb
  - brew uninstall jdcloud_cli
  - brew install --HEAD ./jdcloud_cli.rb
  - brew uninstall jdcloud_cli
cache:
  directories:
    - /usr/local/Homebrew
